# Generated by Django 3.0.7 on 2020-06-22 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cardFirstClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类名')),
                ('priority', models.IntegerField(default=1, verbose_name='优先级')),
            ],
            options={
                'verbose_name': '卡片第一类型',
                'verbose_name_plural': '卡片第一类型',
                'ordering': ('created',),
            },
        ),
    ]
