# Generated by Django 3.0.7 on 2020-06-22 11:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SearchAndNavAPP', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardSecondeClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='类名')),
                ('priority', models.IntegerField(default=1, verbose_name='优先级')),
                ('background', models.CharField(max_length=100, verbose_name='背景')),
                ('class_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SearchAndNavAPP.cardFirstClass', to_field='name', verbose_name='一级分类')),
            ],
            options={
                'verbose_name': '卡片第二类型',
                'verbose_name_plural': '卡片第二类型',
                'ordering': ('created',),
            },
        ),
    ]
