# Generated by Django 3.0.7 on 2020-06-22 11:18

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SearchAndNavAPP', '0002_cardsecondeclass'),
    ]

    operations = [
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='时间')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='网站名')),
                ('priority', models.IntegerField(default=1, verbose_name='优先级')),
                ('url', models.TextField(verbose_name='网址')),
                ('description', models.CharField(max_length=100, verbose_name='描述')),
                ('logo', models.TextField()),
                ('awesome', models.IntegerField(default=0, verbose_name='点赞')),
                ('click', models.IntegerField(default=0, verbose_name='点击量')),
                ('card_class_first', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SearchAndNavAPP.cardFirstClass', to_field='name', verbose_name='一级分类')),
                ('card_class_second', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SearchAndNavAPP.cardSecondeClass', to_field='name', verbose_name='二级分类')),
            ],
            options={
                'verbose_name': '卡片',
                'verbose_name_plural': '卡片',
                'ordering': ('created',),
            },
        ),
    ]
