# Generated by Django 3.0.7 on 2020-06-23 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchAndNavAPP', '0003_card'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardsecondeclass',
            name='background',
            field=models.CharField(max_length=300, verbose_name='背景'),
        ),
    ]
