# Generated by Django 3.0.7 on 2020-06-23 07:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SearchAndNavAPP', '0006_auto_20200623_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='card',
            options={'ordering': ('-priority',), 'verbose_name': '卡片', 'verbose_name_plural': '卡片'},
        ),
        migrations.AlterModelOptions(
            name='cardfirstclass',
            options={'ordering': ('-priority',), 'verbose_name': '卡片第一类型', 'verbose_name_plural': '卡片第一类型'},
        ),
        migrations.AlterModelOptions(
            name='cardsecondeclass',
            options={'ordering': ('-priority',), 'verbose_name': '卡片第二类型', 'verbose_name_plural': '卡片第二类型'},
        ),
    ]
