# Generated by Django 3.0.7 on 2020-06-24 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchAndNavAPP', '0008_auto_20200623_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='lable',
            field=models.CharField(default='null', max_length=100, verbose_name='标签'),
        ),
    ]
