# Generated by Django 3.0.7 on 2020-06-24 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SearchAndNavAPP', '0011_auto_20200624_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchsite',
            name='logo',
            field=models.TextField(default='null', null=True),
        ),
    ]
